"""Derived audit report. A pure function of the JSONL data files: regenerate, never hand-edit.

    uv run python -m execution.audit.report --pilot     # -> benchmark/audit/AUDIT_REPORT_pilot.md
    uv run python -m execution.audit.report             # -> benchmark/audit/AUDIT_REPORT.md
"""

from __future__ import annotations

import argparse
import csv
import re
from collections import Counter, defaultdict
from pathlib import Path

from . import config, records
from .audit import bug_ids
from .parse import short_type

STATUSES = ["REPRODUCES", "REPRODUCES_CRASH_ONLY", "FAILS_SETUP", "FAILS_EXPECTED_BEHAVIOR", "FLAKY", "TIMEOUT"]
ABBR = {"REPRODUCES": "REPRO", "REPRODUCES_CRASH_ONLY": "CRASH_ONLY", "FAILS_SETUP": "SETUP",
        "FAILS_EXPECTED_BEHAVIOR": "EXPECTED", "FLAKY": "FLAKY", "TIMEOUT": "TIMEOUT"}


def pct(n, d):
    return f"{100 * n / d:.1f}%" if d else "n/a"


def normalise_error(rec: dict) -> str:
    e = rec.get("error") or ""
    e = re.sub(r"[0-9a-f]{7,40}", "<sha>", e)
    e = re.sub(r"/opt/conda/envs/\w+", "<env>", e)
    e = re.sub(r"'[^']{1,80}'", "'…'", e)
    e = re.sub(r"\d+(\.\d+)?", "N", e)
    return f"{rec['status_reason']}: {e[:110]}"


def fork_2023_baseline() -> dict[tuple[str, int], bool]:
    base = {}
    b, f = config.FORK_DIR / "new-conda-buggy.csv", config.FORK_DIR / "new-conda-fixed.csv"
    if not (b.exists() and f.exists()):
        return base
    fixed = {(r["repo"], int(r["bugid"])): r["result"] for r in csv.DictReader(open(f, encoding="utf-8"))}
    for r in csv.DictReader(open(b, encoding="utf-8")):
        k = (r["repo"], int(r["bugid"]))
        base[k] = r["result"] == "fail" and fixed.get(k) == "pass"
    return base


def load_eligibility(audit_dir: Path) -> dict[tuple[str, int], dict]:
    return {(r["project"], int(r["bug_id"])): r
            for r in records.read_jsonl(audit_dir / "eligibility.jsonl")}  # later lines win


def build(audit_dir: Path, projects: list[str], title: str) -> str:
    latest = records.latest_by_bug(records.read_jsonl(audit_dir / "audit_results.jsonl"))
    events = records.read_jsonl(audit_dir / "project_runs.jsonl")
    elig = load_eligibility(audit_dir)
    recs = [r for (p, _), r in sorted(latest.items()) if p in projects]
    total_bugs = {p: len(bug_ids(p)) for p in projects}
    n_total = sum(total_bugs.values())
    c = Counter(r["status"] for r in recs)
    broad = c["REPRODUCES"] + c["REPRODUCES_CRASH_ONLY"]
    parked = {e["project"] for e in events if e.get("event") == "project_parked"}
    harness = sorted({(r["harness_version"], r["harness_git_sha"][:10], r["image_tag"]) for r in recs})

    L = [f"# {title}", "",
         "> Generated by `execution/audit/report.py` from `audit_results.jsonl`, `project_runs.jsonl` and "
         "`eligibility.jsonl`. Do not edit by hand.", "",
         f"- Generated: {records.utcnow()}",
         f"- Projects in scope: {', '.join(projects)}",
         f"- BugsInPy fork: `{config.FORK_SHA}`",
         f"- Harness / image: {'; '.join(f'v{h} @ {s} / `{t}`' for h, s, t in harness) or 'n/a'}",
         f"- Rules: `{config.RULES_VERSION}` (see EXCLUSION_RULES.md)", ""]

    # ---- headline
    n_eligible = sum(1 for r in recs if r["status"] == "REPRODUCES" and elig.get((r["project"], r["bug_id"]), {}).get("eligible") is True)
    n_classified = sum(1 for r in recs if r["status"] == "REPRODUCES" and (r["project"], r["bug_id"]) in elig)
    pending = "" if n_classified == c["REPRODUCES"] else \
        f" (eligibility classified for {n_classified}/{c['REPRODUCES']} REPRODUCES bugs — PENDING)"
    L += ["## Headline", "",
          f"| Quantity | Count |", "|---|---:|",
          f"| Bugs in scope | {n_total} |",
          f"| Audited | {len(recs)} ({pct(len(recs), n_total)}) |",
          f"| Broad reproduction (REPRODUCES + REPRODUCES_CRASH_ONLY) | {broad} ({pct(broad, len(recs))} of audited) |",
          f"| REPRODUCES (strict failure type) | {c['REPRODUCES']} ({pct(c['REPRODUCES'], len(recs))} of audited) |",
          f"| REPRODUCES_CRASH_ONLY | {c['REPRODUCES_CRASH_ONLY']} ({pct(c['REPRODUCES_CRASH_ONLY'], broad)} of broad) |",
          f"| **REPRODUCES and ELIGIBLE** | **{n_eligible}**{pending} |", ""]
    if n_classified < c["REPRODUCES"] or len(recs) < n_total:
        L += [f"**§6.6 power floor (n ≥ 120): NOT YET DETERMINABLE.** {len(recs)}/{n_total} bugs audited, "
              f"eligibility classified for {n_classified}/{c['REPRODUCES']} REPRODUCES bugs.", ""]
    else:
        met = n_eligible >= 120
        L += [f"**§6.6 power floor (n ≥ 120): {'MET' if met else 'NOT MET'}** — {n_eligible} eligible bugs.", ""]

    # ---- by project
    base = fork_2023_baseline()
    L += ["## Status by project", "",
          "| Project | Bugs | Audited | " + " | ".join(ABBR[s] for s in STATUSES) + " | Broad | Fork 2023 broad* | Wall clock | Debug min |",
          "|---|---:|---:|" + "---:|" * len(STATUSES) + "---:|---:|---:|---:|"]
    for p in projects:
        pr = [r for r in recs if r["project"] == p]
        pc = Counter(r["status"] for r in pr)
        secs = sum(e.get("seconds", 0) for e in events if e.get("project") == p and e.get("event") in ("bug_attempt", "project_prep"))
        dbg = sum(e.get("debug_minutes", 0) for e in events if e.get("project") == p and e.get("event") == "debug")
        b23 = sum(1 for (bp, _), ok in base.items() if bp == p and ok)
        flag = " (TIMEOUT_PROJECT, parked)" if p in parked else ""
        L.append(f"| {p}{flag} | {total_bugs[p]} | {len(pr)} | " + " | ".join(str(pc[s]) for s in STATUSES)
                 + f" | {pc['REPRODUCES'] + pc['REPRODUCES_CRASH_ONLY']} | {b23} | {secs/3600:.2f} h | {dbg:.0f} |")
    L += ["", "\\* Fork's own 2023 run (`new-conda-*.csv`): single run, grep-based, crash failures counted as fail, "
          "over **all** bugs of the project (not only those audited here).", ""]

    # ---- failure causes
    L += ["## Most common failure causes", ""]
    for s in ["FAILS_SETUP", "FAILS_EXPECTED_BEHAVIOR", "FLAKY", "TIMEOUT"]:
        group = [r for r in recs if r["status"] == s]
        if not group:
            continue
        L += [f"### {s} ({len(group)})", "", "| Count | Cause (normalised) | Example |", "|---:|---|---|"]
        by = defaultdict(list)
        for r in group:
            by[normalise_error(r)].append(r)
        for k, rs in sorted(by.items(), key=lambda kv: -len(kv[1]))[:12]:
            L.append(f"| {len(rs)} | `{k.replace('|', '/')}` | {rs[0]['project']}/{rs[0]['bug_id']} |")
        L.append("")

    # ---- crash-only population
    crash = [r for r in recs if r["status"] == "REPRODUCES_CRASH_ONLY"]
    L += ["## Crash-only manifestation (Amendment 002)", "",
          f"{len(crash)} of {broad} broadly reproducing bugs ({pct(len(crash), broad)}) manifest on the buggy version "
          "only through crash-type failures, so no test suite can separate oracle quality on them.", ""]
    cats = Counter()
    for r in crash:
        for run in r["versions"]["buggy"]["runs"][:1]:
            for cmd in run["commands"]:
                for f in cmd["failures"]:
                    cats[(f["category"], short_type(f["exc_type"]) or "?")] += 1
    if cats:
        L += ["| Category | Exception | Failing tests (run 1) |", "|---|---|---:|"]
        L += [f"| {cat} | {exc} | {n} |" for (cat, exc), n in cats.most_common()]
        L.append("")
    assert_only = sum(1 for r in recs if r["status"] == "REPRODUCES" and r["strict"].get("strict_assertion_only"))
    L += [f"Sensitivity (§A.4): under the assertion-only reading, REPRODUCES would be **{assert_only}** instead of "
          f"{c['REPRODUCES']} ({c['REPRODUCES'] - assert_only} bugs manifest via a runtime exception raised by the faulty code).", ""]

    # ---- python version
    L += ["## Status by subject Python version", "", "| Python | " + " | ".join(ABBR[s] for s in STATUSES) + " |",
          "|---|" + "---:|" * len(STATUSES)]
    byv = defaultdict(Counter)
    for r in recs:
        byv[r.get("python_version_declared") or "?"][r["status"]] += 1
    for v in sorted(byv):
        L.append(f"| {v} | " + " | ".join(str(byv[v][s]) for s in STATUSES) + " |")
    L.append("")

    # ---- validity checks
    origin = Counter()
    cov_origin = Counter()
    for r in recs:
        for vn in ("buggy", "fixed"):
            vv = r["versions"].get(vn, {})
            if vv.get("setup_ok"):
                origin[(vn, vv.get("module_origin"))] += 1
        cov = r["versions"].get("buggy", {}).get("coverage")
        if cov:
            cov_origin["+".join(cov.get("origin") or ["none"])] += 1
    pipf = Counter(x for r in recs for vn in ("buggy", "fixed") for x in r["versions"].get(vn, {}).get("pip_failures", []) or [])
    L += ["## Validity checks", "",
          "**Which copy of the project was imported** (probe: `import <pkg>` from the checkout root):", "",
          "| Version | Origin | Bugs |", "|---|---|---:|"]
    L += [f"| {vn} | {o} | {n} |" for (vn, o), n in sorted(origin.items(), key=lambda kv: (kv[0][0], -kv[1]))]
    L += ["", "**Which copy the triggering tests executed** (coverage of patched files, buggy version):", "",
          "| Origin | Bugs |", "|---|---:|"]
    L += [f"| {o} | {n} |" for o, n in cov_origin.most_common()]
    L += ["", "**Most frequent pip install failures** (tolerated by the fork's line-by-line install):", "",
          "| Count (bug-versions) | pip error |", "|---:|---|"]
    L += [f"| {n} | `{e}` |" for e, n in pipf.most_common(10)]
    L.append("")

    # ---- determinism
    det = [r for r in recs if r["status"] == "REPRODUCES"]
    dc = Counter("not run" if not r.get("determinism") or not r["determinism"].get("ran")
                 else ("deterministic" if r["determinism"]["deterministic"] else "nondeterministic") for r in det)
    L += ["## Determinism screen (§4.1 criterion 4, Amendment 001) over REPRODUCES", "",
          "| Result | Bugs |", "|---|---:|"] + [f"| {k} | {n} |" for k, n in dc.most_common()] + [""]

    # ---- eligibility
    L += ["## Eligibility (§4.1 criteria 2–4)", ""]
    if not elig:
        L += ["Not yet classified. The post-hoc classifier runs only after EXCLUSION_RULES.md is final.", ""]
    else:
        crit = Counter()
        for r in det:
            e = elig.get((r["project"], r["bug_id"]))
            if e:
                for k, ok in e.get("criteria", {}).items():
                    crit[(k, ok)] += 1
        L += ["| Criterion | Pass | Fail |", "|---|---:|---:|"]
        for k in sorted({k for k, _ in crit}):
            L.append(f"| {k} | {crit[(k, True)]} | {crit[(k, False)]} |")
        L.append("")
    return "\n".join(L) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pilot", action="store_true")
    ap.add_argument("--audit-dir", default=str(config.AUDIT_DIR))
    ap.add_argument("--projects", nargs="+")
    args = ap.parse_args(argv)
    audit_dir = Path(args.audit_dir)
    if args.pilot:
        projects = args.projects or config.PILOT_PROJECTS
        out, title = audit_dir / "AUDIT_REPORT_pilot.md", "BugsInPy Reproduction Audit — Pilot Report"
    else:
        projects = args.projects or sorted(config.PACKAGE_MAP)
        out, title = audit_dir / "AUDIT_REPORT.md", "BugsInPy Reproduction Audit — Report"
    out.write_text(build(audit_dir, projects, title), encoding="utf-8", newline="\n")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
